[package]
name = "stonkfish"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
numext-fixed-uint = "0.1.6"
derive-new = "0.5.9"
arrayvec="0.7.2"
