[package]
name = "stonkfish"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
numext-fixed-uint = "0.1.6"
derive-new = "0.5.9"
wasm-bindgen = "0.2"